# This file can only be edited inside the uBlue image's git repository.

# The image will be at "ghcr.io/yourusername/name".
name: leo-fedora

# The native container image to build on top of.
# Warning: Non-uBlue images might not work properly, due to missing components.
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 40 # latest is also supported if you want new updates ASAP

# This description will be visible in the container metadata.
description: This is my personal OS image.


modules:
  - type: signing
  - type: script
    snippets:
      - "mkdir -p /opt"
  #- type: bling # configure what to pull in from ublue-os/bling
   #install:
      #- justfiles # add "!include /usr/share/ublue-os/just/100-bling.just"
                  # in your custom.just (added by default) or local justfile
      #- nix-installer # shell shortcuts for determinate system's nix installers
      #- ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - 1password # install 1Password (stable) and `op` CLI tool
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm
      # - gnome-vrr # enables gnome-vrr for your image
      # - container-tools # installs container-related tools onto /usr/bin: kind, kubectx, docker-compose and kubens
      # - laptop # installs TLP and configures your system for laptop usage
      # - flatpaksync # allows synchronization of user-installed flatpaks, see separate documentation section
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

#  - type: akmods
#    install:
#      - xone
#      - xpadneo
#      - winesync

  - type: rpm-ostree
    # A list of urls of ".repo" files that should be added to your system.
    # This is the proper way to add custom COPR repos to your image.
    # Tip: Use `%OS_VERSION%` instead of static Fedora version numbers,
    # so that your repos automatically use your image's actual Fedora version,
    # which greatly simplifies future maintenance of your custom recipe.
    repos:
      # Example (which also demonstrates version number expansion):
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ayoungdukie/Personal_Repo/repo/fedora-%OS_VERSION%/ayoungdukie-Personal_Repo-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/observeroftime/betterdiscordctl/repo/fedora-%OS_VERSION%/observeroftime-betterdiscordctl-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/rob72/86Box/repo/fedora-%OS_VERSION%/rob72-86Box-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/jstaf/onedriver/repo/fedora-%OS_VERSION%/jstaf-onedriver-%OS_VERSION%.repo
      - https://download.opensuse.org/repositories/home:/jejb1:/Element/Fedora_%OS_VERSION%/home:jejb1:Element.repo
      - https://rpm.librewolf.net/librewolf-repo.repo
      - https://copr.fedorainfracloud.org/coprs/mariolimonciello/power-profiles-daemon/repo/fedora-%OS_VERSION%/mariolimonciello-power-profiles-daemon-%OS_VERSION%.repo
      #- http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://rpm.craftcat.dev/leo.repo
      - https://negativo17.org/repos/fedora-multimedia.repo
      - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/erovia/wb32-dfu-updater/repo/fedora-%OS_VERSION%/erovia-wb32-dfu-updater-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/joycond/repo/fedora-%OS_VERSION%/kylegospo-joycond-%OS_VERSION%.repo
      - https://repository.mullvad.net/rpm/stable/mullvad.repo
      - https://copr.fedorainfracloud.org/coprs/varlad/zellij/repo/fedora-%OS_VERSION%/varlad-zellij-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-%OS_VERSION%/tofik-nwg-shell-%OS_VERSION%.repo
    # These RPMs will be installed from your enabled repositories (Fedora's own
    # repos, extra "repos" you've added, etc). The installation is automatically
    # performed via rpm-ostree during the image build, and will be pre-installed
    # at the "system level" in the final image.
    install:
    # Needed for yafti (the first boot installer). Remove if you're not using yafti.
      - python3-pip
      - python3-devel
      - iasl
      # GNOME's GTK4 theme, Libadwaita. Already included in Silverblue, but not
      # other spins. You can remove if you aren't using yafti, but many native
      # apps and binaries require it, so it's a good idea to always include it
      # if you ever download or compile any custom software on your machine.
      - libadwaita
      # Add your own below:
      # Example:
      # - tilix
      - onedrive
      - xwaylandvideobridge
      - distrobox 
      - power-profiles-daemon
        #- libva-intel-driver
      - mesa-va-drivers-freeworld
      - rocminfo
      - rocm-opencl
      - rocm-clinfo
      #- rocclr
      #- mesa-vdpau-drivers-freeworld
      #- mesa-va-drivers-freeworld-23.2.1-2.fc39.x86_64
      #- mesa-va-drivers-1
      - libavcodec-freeworld
      - ffmpeg
      - radeontop
      - gstreamer1-plugin-libav
      - gstreamer1-plugins-bad-free-extras 
      - gstreamer1-plugins-ugly 
      - gstreamer1-vaapi 
      - steam-devices
      - mesa-dri-drivers
      - wezterm
      - appimagelauncher
      #- VirtualBox
      - zsh
      - tailscale
      - neofetch
      - python3-neovim
      - make
      - nodejs
      - plank
      #- intel-gpu-tools
      - lm_sensors
      #- intel-media-driver
      - binutils
      - bat
      - imsettings
      - flameshot
      - onedriver
      - fcitx5-chinese-addons
      - fcitx5-configtool
      - fcitx5-gtk
      - fcitx5-qt
      - fcitx5-table-extra
      - fcitx5-table-other
      - virt-manager
      - virt-viewer
        #- tlp
        #- tlp-rdw
      - powertop
#     - dnf5
#     - dnf5-plugins
      - fedora-packager-kerberos
      - krb5-workstation
      - krb5-pkinit
      - libsecret
     #- librewolf
      - gnome-keyring
      - mailspring
      - fedora-packager
      - fedora-review
      #- rust2rpm
      - copr-cli
      - awscli2
      - libimobiledevice-utils
      - btop
      - gstreamer1-plugin-libav
      - gstreamer1-plugins-bad-free-extras
      - gstreamer1-plugins-bad-freeworld
      - gstreamer1-plugins-ugly
      - gstreamer1-vaapi
      - portaudio-devel
      - freeipa-client
      - xfreerdp
      - rapid-photo-downloader
      - redhat-lsb-core
      - xterm
      - wb32-dfu-updater
      - joycond
      - strongswan
      - proxychains-ng
      - discord
      - mullvad-vpn
      - kalendar
      - zellij
      - hyprland
      - hyprland-plugins
      - xdg-desktop-portal-hyprland
      - hyprland-autoname-workspaces
      - hyprland-contrib
      - hyprpaper
      - hyprpicker
      - hypridle
      - hyprlock
      - hyprshot
      - waybar-git
      - aylurs-gtk-shell
      - cliphist
      - nwg-clipman
      - swww
      - waypaper
      - hyprnome
      - hyprdim
      - swaylock-effects
      - pyprland
      - mpvpaper
      - rofi-wayland
      - nwg-look
      - network-manager-applet
      - brightnessctl
      - parallel
      - dunst
      - swayidle
      - wlogouut
      - pavucontrol
      - qt6-qtbase-devel
      - kvantum
      - qt6ct
      - qt5ct
      - fastfetch
      
      # These RPMs will be removed from the system image. This step happens during
      # image build, BEFORE installing custom RPMs (from the "rpm.install" category).
    remove:
      # Remove the native firefox (from Fedora) in favor of the Flatpak.
      - firefox
      - firefox-langpacks
      - toolbox
      - lsb_release
       
  - type: default-flatpaks
    notify: true   # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
      # - org.gnome.Loupe
      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
      # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Multiple install of same flatpaks with different branches is not supported.
      - org.freedesktop.Platform.VulkanLayer.gamescope
      - io.github.celluloid_player.Celluloid
      - org.kde.krita
      - com.github.tchx84.Flatseal
      - com.github.zadam.trilium
      - com.moonlight_stream.Moonlight
      - com.spotify.Client
      - com.valvesoftware.SteamLink
      - com.yubico.yubioath
      - org.localsend.localsend_app
      - org.prismlauncher.PrismLauncher
      - org.bluesabre.MenuLibre
      - org.libreoffice.LibreOffice
#    - io.gitlab.librewolf-community
      #- org.freedesktop.Platform.ffmpeg-full
      - com.discordapp.Discord
      - com.github.Eloston.UngoogledChromium
      - com.github.Matoking.protontricks
      - com.github.d4nj1.tlpui
      - com.github.jeromerobert.pdfarranger
      - com.github.xournalpp.xournalpp
      - dev.krtirtho.Flemozi
      - io.github.seadve.Kooha
      - io.missioncenter.MissionCenter
      - net.lutris.Lutris
      - org.freedesktop.Platform.VulkanLayer.MangoHud
      - org.godotengine.Godot
      - org.gustavoperedo.FontDownloader
      - org.kicad.KiCad
      remove:
      # - org.gnome.eog
      #
    # A flatpak repo can also be added without having to install flatpaks,
    # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub

